export const ProcurementState = {
  PROCUREMENT_DRAFT: 'PROCUREMENT_DRAFT',
  PROCUREMENT_PENDING_QUOTE: 'PROCUREMENT_PENDING_QUOTE',
  PROCUREMENT_QUOTED: 'PROCUREMENT_QUOTED',
  PROCUREMENT_PENDING_APPROVAL: 'PROCUREMENT_PENDING_APPROVAL',
  PROCUREMENT_APPROVED: 'PROCUREMENT_APPROVED',
  PROCUREMENT_ORDERED: 'PROCUREMENT_ORDERED',
  PROCUREMENT_PARTIALLY_RECEIVED: 'PROCUREMENT_PARTIALLY_RECEIVED',
  PROCUREMENT_RECEIVED: 'PROCUREMENT_RECEIVED',
  PROCUREMENT_REJECTED: 'PROCUREMENT_REJECTED',
  PROCUREMENT_CANCELLED: 'PROCUREMENT_CANCELLED',
} as const;

export type ProcurementState = (typeof ProcurementState)[keyof typeof ProcurementState];

export const PROCUREMENT_STATE_LABELS: Record<ProcurementState, string> = {
  PROCUREMENT_DRAFT: '草稿',
  PROCUREMENT_PENDING_QUOTE: '待询价',
  PROCUREMENT_QUOTED: '已询价',
  PROCUREMENT_PENDING_APPROVAL: '待审批',
  PROCUREMENT_APPROVED: '已批准',
  PROCUREMENT_ORDERED: '已下单',
  PROCUREMENT_PARTIALLY_RECEIVED: '部分到货',
  PROCUREMENT_RECEIVED: '已到货',
  PROCUREMENT_REJECTED: '已驳回',
  PROCUREMENT_CANCELLED: '已作废',
};
