export default defineAppConfig({
  pages: [
    'pages/login/index',
    'pages/home/index',
    'pages/orders/index',
    'pages/order-create/index',
    'pages/order-detail/index',
    'pages/sign-in/index',
    'pages/fault-confirm/index',
    'pages/receipt/index',
    'pages/signature/index',
    'pages/approvals/index',
    'pages/approval-detail/index',
    'pages/warehouse/index',
    'pages/pick-form/index',
    'pages/pick-detail/index',
    'pages/return-form/index',
    'pages/return-detail/index',
    'pages/procurements/index',
    'pages/procurement-form/index',
    'pages/procurement-detail/index',
    'pages/profile/index',
    'pages/report/index',
  ],
  tabBar: {
    custom: true,
    color: '#64748b',
    selectedColor: '#60a5fa',
    backgroundColor: '#1a1d24',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: 'assets/tabs/home.png',
        selectedIconPath: 'assets/tabs/home-active.png',
      },
      {
        pagePath: 'pages/orders/index',
        text: '工单',
        iconPath: 'assets/tabs/order.png',
        selectedIconPath: 'assets/tabs/order-active.png',
      },
      {
        pagePath: 'pages/approvals/index',
        text: '审批',
        iconPath: 'assets/tabs/approval.png',
        selectedIconPath: 'assets/tabs/approval-active.png',
      },
      {
        pagePath: 'pages/warehouse/index',
        text: '仓库',
        iconPath: 'assets/tabs/warehouse.png',
        selectedIconPath: 'assets/tabs/warehouse-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/tabs/profile.png',
        selectedIconPath: 'assets/tabs/profile-active.png',
      },
    ],
  },
  window: {
    backgroundTextStyle: 'dark',
    navigationBarBackgroundColor: '#1a1d24',
    navigationBarTitleText: 'Kinho',
    navigationBarTextStyle: 'white',
  },
})
