ALTER TABLE "CustomerRequest" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "CustomerRequest" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
ALTER TABLE "CustomerRequest" ADD COLUMN IF NOT EXISTS "locationAccuracy" DOUBLE PRECISION;
